<a href="https://colab.research.google.com/github/adigun3/Data-Science/blob/master/AirQuality_data_artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
dataset = pd.read_excel('AirQualityUCI_data.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)


[[   2.6        1360.          150.         ... 1692.
  1267.5          13.5999999 ]
 [   2.         1292.25        112.         ... 1558.75
   972.25         13.29999995]
 [   2.2        1402.           88.         ... 1554.5
  1074.           11.9000001 ]
 ...
 [   2.4        1142.         -200.         ... 1240.75
  1092.           26.89999962]
 [   2.1        1002.5        -200.         ... 1041.
   769.75         28.32499981]
 [   2.2        1070.75       -200.         ... 1128.5
   816.           28.50000048]]


In [8]:
print(y)


[0.75775383 0.72548745 0.75023907 ... 0.64064877 0.51386592 0.50280371]


### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
print(X_test)



[[ 1.30e+00  9.16e+02  1.01e+02 ...  1.31e+03  6.04e+02  1.88e+01]
 [ 6.00e-01  9.18e+02 -2.00e+02 ...  8.17e+02  7.12e+02  6.07e+00]
 [ 4.00e-01  7.66e+02 -2.00e+02 ...  1.31e+03  5.30e+02  2.15e+01]
 ...
 [ 2.60e+00 -2.00e+02  2.62e+02 ... -2.00e+02 -2.00e+02 -2.00e+02]
 [ 9.00e-01  9.99e+02 -2.00e+02 ...  1.38e+03  5.94e+02  1.25e+01]
 [ 1.70e+00  9.91e+02 -2.00e+02 ...  1.41e+03  8.06e+02  3.16e+01]]


In [18]:
print(y_test)

[   0.68    0.41    1.16 ... -200.      1.      1.16]


## Part 2 - Building the ANN

### Initializing the ANN

In [0]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [0]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [0]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [0]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

### Predicting the results of the Test set

In [16]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[   1.03    0.68]
 [   1.03    0.41]
 [   1.03    1.16]
 ...
 [-199.96 -200.  ]
 [   1.03    1.  ]
 [   1.03    1.16]]
