<a href="https://colab.research.google.com/github/adigun3/Data-Science/blob/master/AirQuality%20data%20multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [0]:
dataset = pd.read_csv('AirQualityUCI.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[   2.6 1360.   150.  ... 1692.  1268.    13.6]
 [   2.  1292.   112.  ... 1559.   972.    13.3]
 [   2.2 1402.    88.  ... 1555.  1074.    11.9]
 ...
 [   2.4 1142.  -200.  ... 1241.  1092.    26.9]
 [   2.1 1003.  -200.  ... 1041.   770.    28.3]
 [   2.2 1071.  -200.  ... 1129.   816.    28.5]]


In [4]:
print(y)

[0.7578 0.7255 0.7502 ... 0.6406 0.5139 0.5028]


## Encoding categorical data

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [0]:
print(X)

## Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Multiple Linear Regression model on the Training set

In [6]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [7]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 4.52e-01  6.82e-01]
 [ 2.76e+00  4.13e-01]
 [ 2.20e+00  1.16e+00]
 ...
 [-1.99e+02 -2.00e+02]
 [-1.09e-02  1.00e+00]
 [ 1.59e+00  1.16e+00]]
