<a href="https://colab.research.google.com/github/adigun3/Data-Science/blob/master/Classification_artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [0]:
dataset = pd.read_csv('banknote_authentication_data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]


In [5]:
print(y)

[0 0 0 ... 1 1 1]


### Encoding categorical data

Label Encoding the "Gender" column

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [0]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [0]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
print(X_test)

[[-0.77000464 -2.18217308  2.08030018  0.08130195]
 [ 1.65638872 -0.32963963 -0.24955469  1.09660204]
 [-0.85562469  0.31202402 -0.78293531 -1.301957  ]
 ...
 [-0.90845183  0.19704581 -0.89473831 -0.59885426]
 [ 0.02407911  0.29131655 -1.3598972  -1.26353714]
 [-1.68223069  0.72303272 -0.19163475 -2.05646189]]


## Part 2 - Building the ANN

### Initializing the ANN

In [0]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [0]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [0]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [0]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
35/35 [==============================] - 0s 1ms/step - loss: 2.1012e-04 - accuracy: 1.0000
Epoch 2/100
35/35 [==============================] - 0s 1ms/step - loss: 2.0602e-04 - accuracy: 1.0000
Epoch 3/100
35/35 [==============================] - 0s 1ms/step - loss: 2.0361e-04 - accuracy: 1.0000
Epoch 4/100
35/35 [==============================] - 0s 1ms/step - loss: 2.0276e-04 - accuracy: 1.0000
Epoch 5/100
35/35 [==============================] - 0s 1ms/step - loss: 1.9786e-04 - accuracy: 1.0000
Epoch 6/100
35/35 [==============================] - 0s 1ms/step - loss: 1.8856e-04 - accuracy: 1.0000
Epoch 7/100
35/35 [==============================] - 0s 1ms/step - loss: 1.9203e-04 - accuracy: 1.0000
Epoch 8/100
35/35 [==============================] - 0s 1ms/step - loss: 1.8926e-04 - accuracy: 1.0000
Epoch 9/100
35/35 [==============================] - 0s 1ms/step - loss: 1.7751e-04 - accuracy: 1.0000
Epoch 10/100
35/35 [==============================] - 0s 1ms/step - loss:

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [0]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

### Making the Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[157   0]
 [  0 118]]


1.0