<a href="https://colab.research.google.com/github/adigun3/Data-Science/blob/master/Model_decision_tree_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Decision Tree Classification

## Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [0]:
dataset = pd.read_csv('banknote_authentication_data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [4]:
print(X_train)

[[-1.2943    2.6735   -0.84085  -2.0323  ]
 [-0.40857   3.0977   -2.9607   -2.6892  ]
 [-1.5228   -6.4789    5.7568    0.87325 ]
 ...
 [ 0.6005    0.99945  -2.2126    0.097399]
 [ 2.0165   -0.25246   5.1707    1.0763  ]
 [-2.0759   10.8223    2.6439   -4.837   ]]


In [5]:
print(y_train)

[1 1 1 ... 1 0 0]


In [6]:
print(X_test)

[[ -1.7713   -10.7665    10.2184    -1.0043  ]
 [  5.1321    -0.031048   0.32616    1.1151  ]
 [ -2.0149     3.6874    -1.9385    -3.8918  ]
 ...
 [ -2.1652     3.0211    -2.4132    -2.4241  ]
 [  0.48797    3.5674    -4.3882    -3.8116  ]
 [ -4.3667     6.0692     0.57208   -5.4668  ]]


In [7]:
print(y_test)

[1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 0 0
 1 0 1 0 1 0 0 1 1 0 0 1 0 0 1 0 1 1 0 1 1 0 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0
 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0
 1 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1 0
 0 1 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 1 0 1 1 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0
 1 0 1 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0
 0 0 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1 1
 1 0 0 0 1 0 0 1 1 0 1 1 0 1 1 1]


## Feature Scaling

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
print(X_train)

[[-0.60234962  0.13706318 -0.52441296 -0.41116219]
 [-0.291035    0.21026408 -1.02368742 -0.72585061]
 [-0.68266235 -1.4422953   1.02948859  0.98074362]
 ...
 [ 0.06363093 -0.15181461 -0.8474923   0.60907164]
 [ 0.5613238  -0.36784698  0.89144827  1.07801487]
 [-0.87706484  1.54323822  0.29632752 -1.75475574]]


In [10]:
print(X_test)

[[-0.77000464 -2.18217308  2.08030018  0.08130195]
 [ 1.65638872 -0.32963963 -0.24955469  1.09660204]
 [-0.85562469  0.31202402 -0.78293531 -1.301957  ]
 ...
 [-0.90845183  0.19704581 -0.89473831 -0.59885426]
 [ 0.02407911  0.29131655 -1.3598972  -1.26353714]
 [-1.68223069  0.72303272 -0.19163475 -2.05646189]]


## Training the Decision Tree Classification model on the Training set

In [11]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

## Predicting a new result

In [0]:
print(classifier.predict(sc.transform([[30,87000]])))

[0]


## Predicting the Test set results

In [0]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

## Making the Confusion Matrix

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[154   3]
 [  1 117]]


0.9854545454545455

## Visualising the Training set results

## Visualising the Test set results